name: Check for new tags and create PR

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  check-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ 'dev', 'release/aptos-light-client' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can perform a rebase

      - name: Fetch latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/aptos-labs/aptos-core/releases" | jq -r '.[] | select(.name | ascii_downcase | contains("mainnet")) | .tag_name' | grep '^aptos-node-v' | sort -V | tail -n 1)
          CURRENT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [[ $(echo -e "$CURRENT_TAG\n$LATEST_TAG" | sort -V | tail -n 1) != $CURRENT_TAG ]]; then
            echo "name=tag::${LATEST_TAG}" | tee -a $GITHUB_OUTPUT
          else
            echo "The current tag is up to date."
            exit 0
          fi

      - name: Compare and rebase
        id: rebase
        continue-on-error: true
        run: |
          CURRENT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout ${{ matrix.branch }}
          git checkout -b rebase-branch-${{ matrix.branch }}
          if ! git rebase --onto ${{ steps.latest-tag.outputs.tag }} $CURRENT_TAG; then
            echo "Rebase conflicts detected on branch ${{ matrix.branch }}. Please resolve them manually."
            exit 1
          fi
          git push origin rebase-branch-${{ matrix.branch }}

      - name: Create Issue
        if: ${{ failure() && steps.rebase.outcome == 'failure' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ matrix.branch }}
          TAG: ${{ steps.latest-tag.outputs.tag }}

      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Rebase on new tag ${{ steps.latest-tag.outputs.tag }}'
          branch: 'rebase-branch-${{ matrix.branch }}'
          base: '${{ matrix.branch }}'